Repository wakmusic/wakmusic-pc, pull requests merged in 2023-08, with the labels that each got.

#77 :sparkles: 스페이스 바로 노래 틀고 끄기
  src/components/header/Search.tsx
  src/components/modals/CreateListModal/index.tsx
  src/components/modals/LoadListModal/index.tsx
  src/components/player/Controller.tsx
  src/hooks/createListModal.ts
  src/hooks/loadListModal.ts
  src/hooks/player.ts
  src/state/player/atoms.ts
Labels: ✨ Feature

#87 몇몇 페이지 api 작업
  src/apis/artist/index.ts
  src/apis/charts/index.ts
  src/apis/playlist/index.ts
  src/apis/songs/index.ts
  src/components/globals/UpdatedText.tsx
  src/components/index/Chart.tsx
  src/components/index/RecommendItem.tsx
  src/main.tsx
  src/pages/artists/Artist.tsx
  src/pages/chart/Chart.tsx
  src/pages/index/Index.tsx
  src/pages/search/Search.tsx
  src/pages/user/Playlist.tsx
  src/templates/playlist.ts
  src/templates/song.ts
  src/utils/staticUtill.ts
Labels: 📬 API

#91 ✨ PretendardJP 추가
  public/fonts/PretendardJP-Medium.woff2
  src/components/Typography/Default.ts
  src/index.css
Labels: ✨ Feature

#92 🐛 분리모드 체크 시스템 버그 해결
  src/electron.ts
Labels: 🐞 BugFix

#99 👽️ 새로운 검색 API 적용
  src/apis/songs/index.ts
  src/components/search/Result.tsx
  src/components/search/tabs/List.tsx
  src/hooks/infiniteScrollHandler.ts
  src/hooks/scrollToTop.ts
  src/pages/artists/Artist.tsx
  src/pages/new/New.tsx
  src/pages/search/Search.tsx
  src/templates/search.ts
Labels: 📬 API, 🔨 Refactor

#98 💫 추천 아이템 애니메이션 구현
  src/components/index/RecommendItem.tsx
  src/pages/index/Index.tsx
  src/utils/listChunk.ts
Labels: ✨ Feature

#105 ✨ 좋아요 페이지 개발, 앱바 기능구현, 곡 순서 편집 기능
  src/components/globals/CustomSongs.tsx
  src/components/globals/SongItem.tsx
  src/components/globals/Tab.tsx
  src/components/globals/musicControllers/AddMusic.tsx
  src/components/globals/musicControllers/AddPlaylist.tsx
  src/components/globals/musicControllers/DeleteMusic.tsx
  src/components/globals/musicControllers/MusicController.tsx
  src/components/globals/musicControllers/PlayMusic.tsx
  src/components/globals/musicControllers/SelectAll.tsx
  src/components/globals/musicControllers/musicControllerContainers/MusicControllerBar.tsx
  src/components/globals/musicControllers/musicControllerContainers/MusicControllerPlayer.tsx
  src/components/player/Controller.tsx
  src/components/search/SongCard.tsx
  src/components/search/tabs/All.tsx
  src/components/search/tabs/List.tsx
  src/components/user/Header.tsx
  src/constants/dummys.ts
  src/hooks/scrollToTop.ts
  src/hooks/selectSongs.ts
  src/pages/artists/Artist.tsx
  src/pages/chart/Chart.tsx
  src/pages/new/New.tsx
  src/pages/user/Likes.tsx
  src/pages/user/Playlist.tsx
  src/templates/musicController.ts
  src/templates/song.ts
  src/templates/songItem.ts
Labels: ✨ Feature

#145 👽️ FAQ api 연결
  src/apis/faq/dto.ts
  src/apis/faq/index.ts
  src/apis/qna/index.ts
  src/components/faq/Section.tsx
  src/pages/faq/Faq.tsx
  src/templates/faq.ts
Labels: 📬 API

#171 🐛 CustomSongs children 동기화 버그
  src/components/globals/CustomSongs.tsx
Labels: 🐞 BugFix
