Repository wakmusic/wakmusic-pc, pull requests merged in 2023-07, with the labels that each got.

#39 내 리스트 페이지 UI 작업
  src/components/user/header.tsx
  src/components/user/playlist/Menu.tsx
  src/components/user/playlist/MenuItem.tsx
  src/components/user/playlist/PlaylistItem.tsx
  src/constants/dummys.ts
  src/constants/tabs.ts
  src/main.tsx
  src/pages/user/Likes.tsx
  src/pages/user/Playlist.tsx
  src/pages/user/User.tsx
Labels: 🎨 Html&css

#50 ✨ 포매팅 유틸
  src/utils/formatting.ts
Labels: ✨ Feature

#44 ♻️ : MusicController 완성
  src/components/globals/musicControllers/musicControllerContainers/MusicControllerBar.tsx
  src/components/globals/musicControllers/musicControllerContainers/MusicControllerPlayer.tsx
  src/pages/chart/Chart.tsx
Labels: ✨ Feature, 🔨 Refactor
