Repository wakmusic/wakmusic-pc, pull requests merged in 2023-09, with the labels that each got.

#255 :construction_worker: 액션 이름 수정 & 빌드 액션 통합
  .github/workflows/build.yml
  .github/workflows/build_mac.yml
  .github/workflows/build_web.yml
  .github/workflows/check.yml
  forge.config.ts
  package.json
Labels: 🌏 Deploy

#254 ⚡️ SelectSongs, CustomSongs 최적화
  src/components/globals/CustomSongs.tsx
  src/components/globals/SongItem.tsx
  src/components/globals/musicControllers/MusicController.tsx
  src/components/player/Default/Playlist.tsx
  src/components/search/tabs/All.tsx
  src/components/search/tabs/List.tsx
  src/hooks/selectSongs.ts
  src/pages/artists/Artist.tsx
  src/pages/chart/Chart.tsx
  src/pages/new/New.tsx
  src/pages/playerPlaylist/PlayerPlaylist.tsx
  src/pages/user/Likes.tsx
  src/pages/user/Playlist.tsx
  src/templates/song.ts
Labels: 🐞 BugFix, 🔨 Refactor

#260 :sparkles: Shift로 다중선택
  src/hooks/selectSongs.ts
Labels: ✨ Feature
